### ISSUE TITLE
[Improvement]: Add Deployment Project Live Demo Link in Repository About Section

### ISSUE THREAD

**Issue by NarendraKoya999** [Stoccoin-Official/Stoccoin-Website#302]
### Issue Description:
- **Add Deployment Project Live Demo Link in Repository About Section.**

### Screenshot:
![stoccoin-1](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/84512164/ec609b51-0269-4c10-ace1-6af43176a6bf)

### Advantage:
- **It's Easy to Navigate for Live Project To Visited Users and Gives Basic Idea about Project without Forking The Repository.**

**Comment by royalpinto007** [comment]
Hi @NarendraKoya999 
We understand completely that this feature is essential. However, since the project is still in the development stage and there are many aspects that require attention, we will make sure to include a deployment link once we have completed work on the essential features of the website. 
Thank you for your understanding!
